---

- name: deploy virtual machines
  hosts: [localhost]
  connection: local
  vars:
    ssh_key: privnet
    num_nodes: 3
    dhcp_name: privnet-dhcp-server
    security_group_name: privnet
    template: Linux Ubuntu 16.04 LTS 64-bit
    template_filter: featured
    instance_type: Micro
    root_disk_size: 10
    zone: ch-gva-2
    private_network: "dhcp-privnet-{{ zone }}"
  roles:
    - common
    - infra
  tags: common, infra

- name: configure DHCP server
  hosts: [privnet_dhcp]
  vars:
    - dhcp:
        privnet_address: 10.11.12.1/27
        subnet: 10.11.12.0
        netmask: 255.255.255.224
        start: 10.11.12.2
        end: 10.11.12.30
  roles:
    - dhcp/server
  tags: server

- name: configure sample vms
  hosts: [privnet_nodes]
  roles:
    - dhcp/client
  tags: client

- name: README
  hosts: [localhost]
  connection: local
  gather_facts: False
  tasks:
    - debug:
        msg: "You can log on the machines with:
          ssh -i ~/.ssh/id_rsa_privnet ubuntu@<VM-IP>"
  tags: readme