---

- name: "dhcp server : create"
  local_action:
    module: cs_instance
    name: "{{ dhcp_name }}"
    template: "{{ template }}"
    root_disk_size: "{{ root_disk_size }}"
    service_offering: "{{ instance_type }}"
    ssh_key: "{{ ssh_key }}"
    security_groups: [ '{{ security_group_name }}' ]
    user_data: |
      #cloud-config
      manage_etc_hosts: true
      fqdn: {{ dhcp_name }}
    zone: "{{ zone }}"
  register: privnet_dhcp

- name: "sample vms : create {{ num_nodes }} vms"
  local_action:
    module: cs_instance
    name: "privnet-{{ item }}"
    template: "{{ template }}"
    root_disk_size: "{{ root_disk_size }}"
    service_offering: "{{ instance_type }}"
    ssh_key: "{{ ssh_key }}"
    security_groups: [ '{{ security_group_name }}' ]
    user_data: |
      #cloud-config
      manage_etc_hosts: true
      fqdn: privnet-{{ item }}
    zone: "{{ zone }}"
  with_sequence: count={{ num_nodes }}
  when: num_nodes is defined
  register: infra_jobs
  async: 3600
  poll: 0

- name: "wait for samples vms to be ready"
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: privnet_nodes
  until: privnet_nodes.finished
  retries: 300
  with_items: "{{ infra_jobs.results }}"
  when: infra_jobs is defined
