---

- name: "dhcp server : create"
  local_action:
    module: cs_instance
    name: "{{ zone }}-{{ dhcp_name }}"
    template: "{{ template }}"
    root_disk_size: "{{ root_disk_size }}"
    service_offering: "{{ instance_type }}"
    ssh_key: "{{ ssh_key }}"
    security_groups: [ '{{ security_group_name }}' ]
    networks:
      - "{{ private_network }}"
    user_data: |
      #cloud-config
      manage_etc_hosts: true
      fqdn: {{ zone }}-{{ dhcp_name }}
    zone: "{{ zone }}"
  register: privnet_dhcp

- name: "sample vms : create {{ num_nodes }} vms"
  local_action:
    module: cs_instance
    name: "{{ zone }}-privnet-{{ item }}"
    template: "{{ template }}"
    root_disk_size: "{{ root_disk_size }}"
    service_offering: "{{ instance_type }}"
    ssh_key: "{{ ssh_key }}"
    security_groups: [ '{{ security_group_name }}' ]
    networks:
      - "{{ private_network }}"
    user_data: |
      #cloud-config
      manage_etc_hosts: true
      fqdn: {{ zone }}-privnet-{{ item }}
    zone: "{{ zone }}"
  with_sequence: count={{ num_nodes }}
  when: num_nodes is defined
  register: infra_jobs
  async: 3600
  poll: 0

- name: wait for samples vms to be ready
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: privnet_nodes
  until: privnet_nodes.finished
  retries: 300
  with_items: "{{ infra_jobs.results }}"
  when: infra_jobs is defined

- name: wait for SSH to be up
  wait_for:
    port: 22
    host: "{{ privnet_dhcp.default_ip }}"
    sleep: 5
