# Add second Nic to virtual machine for private networking

- name: Add NIC to virtual machine
  local_action:
    module: cs_nic
    network: privNetForBasicZone
    vm: "privnet-{{ item }}"
    zone: "{{ zone }}"
  with_sequence: count={{ num_nodes }}
