---
# Add second Nic to virtual machine for private networking

- name: "dhcp server : add privnet nic"
  local_action:
    module: cs_instance_nic
    network: "{{ private_network }}"
    vm: "{{ privnet_dhcp.name }}"
    zone: "{{ zone }}"

- name: "sample vms : add privnet nic to sample vms"
  local_action:
    module: cs_instance_nic
    network: "{{ private_network }}"
    vm: "{{ item.name }}"
    zone: "{{ zone }}"
  with_items: "{{ privnet_nodes.results }}"
  register: nic_jobs
  async: 3600
  poll: 0

- name: "wait for nics to be ready"
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: nics
  until: nics.finished
  retries: 300
  with_items: "{{ nic_jobs.results }}"
  when: nic_jobs is defined
