---
  - import_tasks: create_secgroup.yml
  - import_tasks: create_secgroup_rules.yml
  - import_tasks: create_private_network.yml
  - import_tasks: create_vm.yml
  - import_tasks: create_private_nic.yml
  - import_tasks: create_inv.yml
