---

- name: create ssh key
  local_action:
    module: cs_sshkeypair
    name: "{{ ssh_key }}"
  register: key
  tags: sshkey

- name: copy ssh key content locally
  local_action: copy content="{{ key.private_key }}" dest="~/.ssh/id_rsa_{{ ssh_key }}"
  when: key.changed
  tags: sshkey

- name: set ssh key file attributes
  file: path="~/.ssh/id_rsa_{{ ssh_key }}" mode=0600
  when: key.changed
  tags: sshkey
