---

- name: install packages
  apt:
    name:
      - isc-dhcp-server
    state: present
    autoclean: yes
    update_cache: yes

- name: set listening interfaces
  lineinfile:
    path: /etc/default/isc-dhcp-server
    line: "INTERFACES=\"eth1\""
    regexp: "^INTERFACES"
  notify: restart dhcp server

- name: set configuration
  template:
    dest: /etc/dhcp/dhcpd.conf
    src: dhcpd.conf.j2
    owner: root
    group: root
  notify: restart dhcp server
